### ISSUE TITLE
where is the requirements.txt for this?

### ISSUE THREAD

**Issue by TanvirHafiz** [1038lab/ComfyUI-OmniGen#10]
open the terminal on the ComfyUI/custom_nodes/AILab_OmniGen folder
..\..\..\python_embeded\python.exe -m pip install -r requirements.txt

there are no requirements as there is no AILab_omnigen folder and hence no requirements.txt!!!!

**Comment by 1038lab** [comment]
it should be  ComfyUI/custom_nodes/ComfyUI-OmniGen
