### ISSUE TITLE
omfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\LLM\OmniGen-v1 does not appear to have a file named config.json

### ISSUE THREAD

**Issue by petersfield1** [1038lab/ComfyUI-OmniGen#11]
Following the recent update I now get the following error

(sorry to be a pain)

**Comment by 1038lab** [comment]
You can remove the LLM/OmniGen-v1, as it will be redownloaded automatically. Alternatively, the faster option is to download it manually here.
https://huggingface.co/Shitao/OmniGen-v1/tree/main
