### ISSUE TITLE
[Feature Request] Add tiled VAE and option to disable K/V cache 

### ISSUE THREAD

**Issue by set-soft** [1038lab/ComfyUI-OmniGen#20]
I guess GGUF is the real solution, but you should add a tiled VAE retry, like in the default VAE decoder of Comfy_UI. BTW: Can you just decouple the VAE decode and take advantage of the automatic tiled VAE? Is really annoying to waste 10 minutes to get a fail at the end because the VAE decode didn't have enough memory.

Another think that can help: https://github.com/chflame163/ComfyUI_OmniGen_Wrapper
Adds an option to disable the K/V cache, it is slower, but reduces the VRAM needed.

**Comment by 1038lab** [comment]
Currently, this model utilizes the SDXL VAE, and I'm unable to modify the underlying structure. Regarding the suggestion to disable the K/V cache, it’s worth noting that under low VRAM conditions, this model already operates slowly, and I'm not sure users would want to invest additional time for image generation.

However, if there’s significant interest in the option to disable the K/V cache, please let me know, and I’ll consider creating a branch for this feature. Your feedback is valuable!

**Comment by set-soft** [comment]
Ok, I created a node with the VAE outside:
https://github.com/set-soft/ComfyUI_OmniGen_Nodes/
