### ISSUE TITLE
issue getting started

### ISSUE THREAD

**Issue by EndoTheDev** [1038lab/ComfyUI-OmniGen#22]
hey so i just installed omni gen and tried running it.
![image](https://github.com/user-attachments/assets/4b1a0cd6-d6c3-4806-bc8b-08f22df6e98d)

it seems omnigen isnt properly loading something from huggingface or something. 
![image](https://github.com/user-attachments/assets/6c4ad175-e5b6-4422-867a-3044e4ba1c62)
its stuck here for at least 20 minutes now. 
any suggestions what i should do?

running in comfyui portable. the rest is working fine.

**Comment by EndoTheDev** [comment]
oh! so it finished. 😅 
![image](https://github.com/user-attachments/assets/bf4d810f-eef0-49c2-bdc9-bf7bafce56b9)
any clue what the issue is?

**Comment by 1038lab** [comment]
updated , try new version
