### ISSUE TITLE
ImportError: cannot import name 'OmniGenPipeline' from 'OmniGen' (unknown location)

### ISSUE THREAD

**Issue by xueqing0622** [1038lab/ComfyUI-OmniGen#3]
after download the hugging face file, still error
Fetching 10 files: 100%|████████████████████████████████████████████████████████████| 10/10 [1:29:35<00:00, 537.57s/it]
OmniGen model downloaded successfully
Error importing OmniGen: cannot import name 'OmniGenPipeline' from 'OmniGen' (unknown location)
!!! Exception during processing !!! Failed to import OmniGen. Please check if the code was downloaded correctly.
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-OmniGen\ailab_OmniGen.py", line 32, in __init__
    from OmniGen import OmniGenPipeline
ImportError: cannot import name 'OmniGenPipeline' from 'OmniGen' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 289, in execute
    obj = class_def()
          ^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-OmniGen\ailab_OmniGen.py", line 36, in __init__
    raise RuntimeError("Failed to import OmniGen. Please check if the code was downloaded correctly.")
RuntimeError: Failed to import OmniGen. Please check if the code was downloaded correctly.

**Comment by 1038lab** [comment]
Some models require additional dependencies to function properly. If the OmniGen model has a requirements.txt file or documentation that lists required packages, make sure those are installed.

`pip install -r requirements.txt`

**Comment by xueqing0622** [comment]
> 某些模型需要额外的依赖项才能正常运行。列出所需包的 requirements.txt 文件或文档，确保已安装这些包。
> 
> ## `pip install -r requirements.txt`
> 您是否在自定义节点文件夹中看到了“OmniGen”。如果没有，请下载它。https [://huggingface.co/spaces/Shitao/OmniGen/tree/main](https://huggingface.co/spaces/Shitao/OmniGen/tree/main)

requirements.txt已经安装，不然comfyui也不会有节点出来的。照上面做了custom_nodes和ComfyUI-OmniGen下面都git clone 了OmniGen，还是一样的错误
