### ISSUE TITLE
Phi3Transformer does not support an attention implementation through torch.nn.functional.scaled_dot_product_attention yet.

### ISSUE THREAD

**Issue by zxtmzxtm** [1038lab/ComfyUI-OmniGen#7]
Phi3Transformer does not support an attention implementation through torch.nn.functional.scaled_dot_product_attention yet. Please request the support for this architecture: https://github.com/huggingface/transformers/issues/28005. If you believe this error is a bug, please open an issue in Transformers GitHub repository and load your model with the argument `attn_implementation="eager"` meanwhile. Example: `model = AutoModel.from_pretrained("openai/whisper-tiny", attn_implementation="eager")`

**Comment by 1038lab** [comment]
its happen because using old version or python, pytorch or CUDA, Update the custom node. it will automatically select between SDPA, eager now.

**Comment by 123LiVo321** [comment]
updated whole comfy, restart, updated all custom nodes, restart, updated just the omnigen node, restart >> still the same error :(

**Comment by Jams63** [comment]
@123LiVo321 same here. updated all and getting same error " File "E:\pinokio\api\comfy.git\app\env\lib\site-packages\transformers\modeling_utils.py", line 1565, in _autoset_attn_implementation
    config = cls._check_and_enable_sdpa(
  File "E:\pinokio\api\comfy.git\app\env\lib\site-packages\transformers\modeling_utils.py", line 1731, in _check_and_enable_sdpa
    raise ValueError(
ValueError: Phi3Transformer does not support an attention implementation through torch.nn.functional.scaled_dot_product_attention yet. Please request the support for this architecture: https://github.com/huggingface/transformers/issues/28005. If you believe this error is a bug, please open an issue in Transformers GitHub repository and load your model with the argument `attn_implementation="eager"` meanwhile. Example: `model = AutoModel.from_pretrained("openai/whisper-tiny", attn_implementation="eager")` "

**Comment by dstults** [comment]
I had the same issue as above but found this thread before I found the other issue that someone opened.

I also had it despite having everything installed and reinstalled brand new in a `conda` environment.

This comment here appears to be the best solution for now, update the OmniGen `config.json` in the models folder:
https://github.com/1038lab/ComfyUI-OmniGen/issues/23#issuecomment-2470903746
