### ISSUE TITLE
OmniGenPipeline.from_pretrained() got an unexpected keyword argument 'attn_implementation'

### ISSUE THREAD

**Issue by petersfield1** [1038lab/ComfyUI-OmniGen#8]
I keep getting the following issue when I try to generate an image using the default workflow

**Comment by ithaqua** [comment]
same as you

> I keep getting the following issue when I try to generate an image using the default workflow

**Comment by axiomgraph** [comment]
Me Too

**Comment by yjuddpl** [comment]
same as you

**Comment by 1038lab** [comment]
Fixed, please update the custom node, if still have issue, let me know
